### ISSUE TITLE
auto scroll

### ISSUE THREAD

**Issue by syrakozz** [caesarcat/InfinitePagingView#16]
could you plz make it auto scroll

**Comment by devforam** [comment]
Use InfinitePagingView's  scrollToNextPage Method by setting Timer:

NSTimer *timer  = [NSTimer scheduledTimerWithTimeInterval:4 target:self selector:@selector(scrollToNextPage) userInfo:nil repeats:YES];

- (void)scrollToNextPage
{
  [self.svPhotoAlbum scrollToNextPage];
}
